apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ege-ingress
  namespace: ege-generator
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ege.example.com
      secretName: ege-tls
  rules:
    - host: ege.example.com
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
