"""initial schema

Revision ID: 1009defd9751
Revises: 
Create Date: 2026-03-28 14:19:06.655302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1009defd9751'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quality_verdict', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_statistics_type_subtype', 'task_statistics', ['task_type', 'subtype'], unique=False)
    op.create_index(op.f('ix_task_statistics_created_at'), 'task_statistics', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_statistics_subtype'), 'task_statistics', ['subtype'], unique=False)
    op.create_index(op.f('ix_task_statistics_task_type'), 'task_statistics', ['task_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_answer', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_wording', sa.Text(), nullable=True),
    sa.Column('total_iterations', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_created_at_desc', 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_subtype'), 'tasks', ['subtype'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_type_created', 'tasks', ['task_type', 'created_at'], unique=False)
    op.create_table('param_generation_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_param_generation_audit_task_id'), 'param_generation_audit', ['task_id'], unique=False)
    op.create_table('task_iterations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('wording', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_stage', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iterations_task_number', 'task_iterations', ['task_id', 'iteration_number'], unique=True)
    op.create_index(op.f('ix_task_iterations_status'), 'task_iterations', ['status'], unique=False)
    op.create_index(op.f('ix_task_iterations_task_id'), 'task_iterations', ['task_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('iteration_id', sa.UUID(), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['iteration_id'], ['task_iterations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_call_type'), 'llm_calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_llm_calls_created_at'), 'llm_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_iteration_id'), 'llm_calls', ['iteration_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_status'), 'llm_calls', ['status'], unique=False)
    op.create_index(op.f('ix_llm_calls_task_id'), 'llm_calls', ['task_id'], unique=False)
    op.create_index('ix_llm_calls_task_type', 'llm_calls', ['task_id', 'call_type'], unique=False)
    op.create_table('task_quality',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iteration_id', sa.UUID(), nullable=False),
    sa.Column('clarity_pass', sa.Boolean(), nullable=False),
    sa.Column('clarity_message', sa.Text(), nullable=True),
    sa.Column('unambiguity_pass', sa.Boolean(), nullable=False),
    sa.Column('unambiguity_message', sa.Text(), nullable=True),
    sa.Column('consistency_pass', sa.Boolean(), nullable=False),
    sa.Column('consistency_message', sa.Text(), nullable=True),
    sa.Column('answer_format_pass', sa.Boolean(), nullable=False),
    sa.Column('answer_format_message', sa.Text(), nullable=True),
    sa.Column('language_correctness_pass', sa.Boolean(), nullable=False),
    sa.Column('language_correctness_message', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('diagnostic_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['task_iterations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_verdict', 'task_quality', ['verdict'], unique=False)
    op.create_index(op.f('ix_task_quality_iteration_id'), 'task_quality', ['iteration_id'], unique=True)
    op.create_index(op.f('ix_task_quality_verdict'), 'task_quality', ['verdict'], unique=False)
    op.create_table('rejection_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quality_profile_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quality_profile_id'], ['task_quality.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejection_criterion', 'rejection_reasons', ['criterion'], unique=False)
    op.create_index('ix_rejection_profile_criterion', 'rejection_reasons', ['quality_profile_id', 'criterion'], unique=False)
    op.create_index(op.f('ix_rejection_reasons_quality_profile_id'), 'rejection_reasons', ['quality_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejection_reasons_quality_profile_id'), table_name='rejection_reasons')
    op.drop_index('ix_rejection_profile_criterion', table_name='rejection_reasons')
    op.drop_index('ix_rejection_criterion', table_name='rejection_reasons')
    op.drop_table('rejection_reasons')
    op.drop_index(op.f('ix_task_quality_verdict'), table_name='task_quality')
    op.drop_index(op.f('ix_task_quality_iteration_id'), table_name='task_quality')
    op.drop_index('ix_quality_verdict', table_name='task_quality')
    op.drop_table('task_quality')
    op.drop_index('ix_llm_calls_task_type', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_task_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_status'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_iteration_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_created_at'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_call_type'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_task_iterations_task_id'), table_name='task_iterations')
    op.drop_index(op.f('ix_task_iterations_status'), table_name='task_iterations')
    op.drop_index('ix_iterations_task_number', table_name='task_iterations')
    op.drop_table('task_iterations')
    op.drop_index(op.f('ix_param_generation_audit_task_id'), table_name='param_generation_audit')
    op.drop_table('param_generation_audit')
    op.drop_index('ix_tasks_type_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_subtype'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_created_at_desc', table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_statistics_task_type'), table_name='task_statistics')
    op.drop_index(op.f('ix_task_statistics_subtype'), table_name='task_statistics')
    op.drop_index(op.f('ix_task_statistics_created_at'), table_name='task_statistics')
    op.drop_index('ix_statistics_type_subtype', table_name='task_statistics')
    op.drop_table('task_statistics')
    # ### end Alembic commands ###
